<a href="https://colab.research.google.com/github/Atharv24-Atreus/Deep-Learning-Lab/blob/main/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np  # Importing the NumPy library for numerical operations

def replace_zeros(sap_id):
    # Convert SAP ID to a string to handle its digits
    sap_str = str(sap_id)

    # Initialize an empty list to hold the replacements for zeros
    replacement = list(sap_str)  # Start with the original digits

    # Count the number of zeros to replace according to rules
    zero_count = replacement.count('0')

    # Replace zeros according to the specified rules
    for i in range(zero_count):
        if i == 0:
            replacement[replacement.index('0')] = '9'  # Replace the first zero with 9
        elif i == 1:
            replacement[replacement.index('0')] = '7'  # Replace the second zero with 7
        elif i == 2:
            replacement[replacement.index('0')] = '5'  # Replace the third zero with 5
        elif i == 3:
            replacement[replacement.index('0')] = '3'  # Replace the fourth zero with 3

    return replacement  # Return the list of replaced digits

def populate_matrix(sap_id):
    # Initialize the matrix with fixed values for the first row
    A = np.array([[6, 4, 0],  # Fixed values for the first row of the matrix
                  [0, 0, 0]])  # Second row initialized with zeros

    # Get the last four digits and replace zeros based on user input (SAP ID)
    replacements = replace_zeros(sap_id)

    # Assign the last four digits to a, b, c, d
    # Make sure to only take the last four digits
    if len(replacements) >= 4:
        a = replacements[-4]  # 1st digit for a
        b = replacements[-3]  # 2nd digit for b
        c = replacements[-2]  # 3rd digit for c
        d = replacements[-1]  # 4th digit for d
    else:
        a, b, c, d = '0', '0', '0', '0'  # Default values if fewer than four digits

    # Fill the matrix with the derived values
    A[0, 2] = a  # Assign a to the 3rd column of the 1st row
    A[1, 0] = b  # Assign b to the 1st column of the 2nd row
    A[1, 1] = c  # Assign c to the 2nd column of the 2nd row
    A[1, 2] = d  # Assign d to the 3rd column of the 2nd row

    return A  # Return the populated matrix

# Example SAP ID for testing
sap_id = 1971  # You can change this to test with different SAP IDs

# Populate the matrix using the given SAP ID
result_matrix = populate_matrix(sap_id)

# Compute the Singular Value Decomposition (SVD) of the matrix
U, S, VT = np.linalg.svd(result_matrix)

# Display the results
print("Final Matrix A:")
print(result_matrix)  # Print the populated matrix

print("\nMatrix U:")
print(U)  # Print the U matrix from SVD

print("\nSingular Values (as a diagonal matrix):")
print(np.diag(S))  # Print the singular values in diagonal form

print("\nMatrix VT:")
print(VT)  # Print the transpose of the V matrix from SVD

Final Matrix A:
[[6 4 1]
 [9 7 1]]

Matrix U:
[[-0.53606351 -0.84417765]
 [-0.84417765  0.53606351]]

Singular Values (as a diagonal matrix):
[[13.55382057  0.        ]
 [ 0.          0.54216958]]

Matrix VT:
[[-0.79785474 -0.59418653 -0.1018341 ]
 [-0.44357767  0.69301926 -0.56829847]
 [-0.40824829  0.40824829  0.81649658]]
